### ISSUE TITLE
Kill `develop` branch in favor of Pull Requests

### ISSUE THREAD

**Issue by augustohp** [Respect/project-info#16]
Merging both branches (`develop` and `master`) was a painful on _Validation_ for version `0.5.0`, after using GitHub for quite some time now (and Git also) I think there isn't much point on having two development branches.

We can always use each others remotes if we want to develop something together by giving write access on out forks.

This will also prevent us from keeping a _develop_ version for too much time as it happened on _Validation_, without releasing it to the public (via a tag with a clear and defined API and semantic version).

What are your thoughts @Respect/troubleshooters ?

**Comment by nickl-** [comment]
I agree if that the two branches should never go out of sync, i.o.w. the master branch moves ahead without rebasing the develop branch.

That said I do feel the use of develop branches are important practical and useful. Master is supposed to be stable release branch, packagist treats it as such. Development is the work in progress, it gives the users a beta release to play with, find the new features they require and report the bugs on allowing more faith in the stable releases. 

Dev branch should always be ahead of master and merging will not be a problem. Fixes can be applied to master (bugs, security issues, typos, show stoppers) as long as dev is rebased and all conflicts rectified so that all new functionality remains ahead. With dev ahead of master merging will always apply smoothly similar to pulling changes.

It is the basic implementation of the feature branch model as introduced by gitflow http://nvie.com/posts/a-successful-git-branching-model/

The problem with remotes is the same problem as with discussions face to face and in private, the community does not get to partake.

**Comment by augustohp** [comment]
I think we have the same objective, just different opinions. I will, also, try to explain myself better a little bit if you don't mind :stuck_out_tongue:

### Workflow with just `master`

My 2 cents on removing the `develop` branch is to keep an always stable (not necessary backwards compatible) branch (as it is today) called `master`. This branch should never be target to general audiences, tags should.

The _development branches_ could be the _pull requests_ instead of a branch which would give us the benefit of the information and code review the Pull Requests page give us, also preventing (and showing) impossible merges.

With Pull Requests, [people can also checkout them](https://help.github.com/articles/checking-out-pull-requests-locally) in order to create another Pull Request to the person who created the Pull Request, so they merge their changes and conversation is centralised on the pull request. This is not straightforward though, some document would help people realise that (or not).

I am also using also the milestones to keep pull requests and issues together, which I think are a straightforward way to show what are our (near) future intentions with the project.

### Problems with `develop` and `master`

Having `develop` always ahead of `master` poses some problems:
1. With a bug fix, we should apply the fix on `master` and `develop`, judging `develop` will have development commits not ready for prime time.
2. When `develop` will be stable enough to a merge with `master` is a hard question to tackle with and it would have no suitable place to hold that discussion history.

### My 2 cents

I think both of them are very similar on effort and results, I just learned that `develop` tends to get too far away from `master` from our experience and that is the only thing (`develop` not going back to `master`) I am trying to avoid here.

I am still not convinced of either way, but I agree with you @nickl- that we should aim (always) to increase community participation! Hurting that, is a "no go" to any option we may have.

**Comment by nickl-** [comment]
@augustohp You make compelling arguments what most strikes me is the problem point 2. you listed but I will respond to 1 as well.

> 1. With a bug fix, we should apply the fix on master and develop, judging develop will have development commits not ready for prime time.

This is easily managed iif the commits are properly flattened and concise to only include the changes for the particular bug or critical issue which can then be cherry picked down to master and development rebased again with the changes still under review. What it requires is contributor education and being strict about the submitted PRs because a multitude of illogical commits or irrelevant changes between commits make it impossible to manage.

> 1. When develop will be stable enough to a merge with master is a hard question to tackle with and it would have no suitable place to hold that discussion history.

Ahh yes... maintenance!!! This is supposed to be someones task, iow a responsible party that is committed to applying the changes back to master. We don't have any of that and currently its more of a close your eyes and cross your fingers lets hope it works.

Doing away with the development branch will result in less maintenance. Yeah! \o/ Doing it properly will be lots of maintenance but perhaps if we pair up and take responsibility in teams then we have more hands to fulfill the tasks.

Will that not risk having a dodgy HEAD giving the appearance that it is sound just prerelease perhaps where dev has the clear meaning that this stuff is currently being worked on. 

It's not an easy choice either way but I will agree that we need a better plan than the way it is currently happening because this way is not sustainable.

**Comment by augustohp** [comment]
> Will that not risk having a dodgy HEAD giving the appearance that it is sound just prerelease perhaps where dev has the clear meaning that this stuff is currently being worked on. 

The "dodgy HEAD" would just became to be if we do merge stuff which is clearly not ready to prime time.

The "working on" issue is a good one. What if, instead of having a fixed `develop` branch we keep `feature/cure-cancer` branches (much like the ones proposed on the [branching model][1] you linked previously)?

It may seem I am holding a grudge against `develop`, and I may be. :blush: I just wish to prevent the rotting of the `master` branch at **any** cost.

**Comment by nickl-** [comment]
I can'n disagree with the `feature/cure-cancer` proposal which solves bot:
- Maintenance issue to merge development into master keep only master
- Semantic meaning for work in progress not ready for prime time. stuff

And not to mention that if succeeis (the cure-cancer part) it will be a nobel price =)

+1 for replacing dev with feature branches. Need a hand?

**Comment by henriquemoody** [comment]
I totally agree on removing `develop` branch and keep only `master`. About the feature `branches`, well, I know it's a PITA to use forks and send a pull request for every change we made but, IMO, it is the best thing to do.
1. It's better to review, even your own code
2. Watchers are notified about the change and also they can review it and comment it
3. We keep the canonical repository clean

Also, there is another thing we must do; we must create branches for supported versions in order to apply fixes, for example, if we are in `0.6` version, then we release `0.7`, we must create a branch called `0.6` and apply every bug fix on it, then merge `0.6` into `0.7` if necessary.

**Comment by henriquemoody** [comment]
It's done in at least the maintained repositories.
